version: '3'
services:
  mysql:
    image: mysql
    ports:
      # To connect from the local machine, use tcp protocol (or the client will default to a socket-based connection that won't work)
      # mysql -h localhost -P <port> --protocol=tcp -u root
      - 3306
      - 33060
    environment:
      MYSQL_ROOT_PASSWORD: admin
  mongo:
    image: mongo
    ports:
      - 27017 # Allow connecting from outside hosts; use docker-compose ps to know the local port it's bound to
  workspace:
    user: workspace
    build:
      context: ./docker/workspace
    volumes:
      - .:/var/www/
    tty: true
    depends_on:
      - mongo
      - mysql
