version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017 # Allow connecting from outside hosts; use docker-compose ps to know the local port it's bound to
  workspace:
    user: workspace
    build:
      context: ./docker/workspace
    volumes:
      - .:/var/www/
    tty: true
    depends_on:
      - mongo
